# Generated by Django 3.0.5 on 2020-04-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200427_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug_category',
            field=models.SlugField(default='N/A', unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.TextField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
