# Generated by Django 3.0.5 on 2020-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200427_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='slug_category',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(default='paralleldesk', max_length=500),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='title',
            field=models.CharField(default='System Admin', max_length=500),
        ),
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(default='Bangalore', max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
